import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import NextAuthProvider from "@/components/session-provider";
import NavigationBar from "@/components/ui/navbar";

const inter = Inter({ subsets: ["latin"] });
const textColor = "text-black dark:text-white";
const backgroundColor = "bg-white dark:bg-black";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + textColor + backgroundColor}>
        <NextAuthProvider>
          <ThemeProvider>
            <NavigationBar />
            {children}
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
